### ISSUE TITLE
December 2017

### ISSUE THREAD

**Issue by jurecuhalev** [ljpy/meetups#10]
# Schedule the meetup

* [x] Talk with Marko from Poligon and choose a date/time when their venue is available. Standard time is Thursday at 7pm, but we don't mind some variation. Book it.
* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/ and use the `Schedule a new Meetup` link to schedule a new meetup.
    * [x] Enter `<Month> <Year>` as `What should we do?`
    * [x] Enter `More details:`. Template:
        ```
        Hi fellow Pythonistas!

        The next Python Meetup will take place on <DAY> <DATE HERE>, at <TIME HERE> in Poligon.

        Speakers: post a comment to https://github.com/ljpy/meetups/issues/1 or send an email to ljpy-organizers@googlegroups.com. First two people to do so get to share their ideas/tips/hacks/rants!

        Sponsors: post a comment to https://github.com/ljpy/meetups/issues/2 or send an email to ljpy-organizers@googlegroups.com. First one to do so gets to be the sponsor!


        See you soon!
        ```
    * [x] Select the booked date and time for the meetup.
    * [x] Select `Hekovnik` as location.
    * [x] When done click `Announce` so members of the user group are notified by email about the upcoming meetup.

# Announce the meetup

Wait a few days. If there are no sponsors and/or speakers that have stepped up, you will have to manually poke them to do so. Go through the list of potential [talks](https://github.com/ljpy/meetups/issues/1) and [sponsors](https://github.com/ljpy/meetups/issues/1). For speakers and sponsors, the rule is First-Come-First-Served: whoever comments on #1 or #2 first, gets to be the speaker/sponsor. Once you have a sponsor and two talks, continue with:

* [ ] Go to https://www.meetup.com/Ljubljana-Python-Group/, click on the upcoming meetup and post the following:
    ```
    Dear Python people of Ljubljana and beyond!

    We are glad to announce the speakers and sponsors for the upcoming Python meetup that will happen on <DAY> <DATE HERE>, at <TIME HERE> in Poligon!

    Talks:
    
    <SPEAKER NAME AND TALK 1 TITLE HERE>

    <SPEAKER NAME AND TALK 2 TITLE HERE>

    After the talks you are welcome to stay around and participate in random discussions with fellow attendees. Free beer will be provided by <SPONSOR NAME HERE>!

    More info and RSVP on <LINK TO MEETUP.COM EVENT HERE>.


    See you there!
    ```
* [ ] Post announcement to https://www.facebook.com/groups/242976319229784/, https://www.facebook.com/groups/522926241218467/, https://www.facebook.com/groups/slotechstud/, https://www.facebook.com/groups/158003467603274/, https://www.facebook.com/groups/6884481293/, https://www.facebook.com/groups/353060628229741, https://www.facebook.com/groups/165720846803088.
* [x] Submit the event to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_event
* [ ] Tweet with @python_lj account:
    ```
    Next #python #meetup in #ljubljana coming soon! <LINK TO MEETUP.COM EVENT HERE>
    ```

# Narrate the meetup

* [ ] Come to Hekovnik 20 minutes before the start of the meetup.
* [ ] Open up the Meetup.com event page on the projector so that new people know they are in the right place.
* [ ] Decide on a provisional date for next meetup.
* [ ] Ask each speaker for a sentence or two about who they are and what they do. Tell them you need this so you can introduce them.
* [ ] Coordinate with speakers who will go first.
* [ ] If the sponsor is attending, ask them to prepare a 3 minute pitch about what they do and (potentially) who they are looking for.
* [ ] The schedule is normally something along these lines. Feel free to improvise:
  * [ ] "Raise hand if you are new to this meetup".
  * [ ] "Raise hand if you are new to Python".
  * [ ] Introduce the sponsor and give them 3 minutes for their pitch.
  * [ ] Cross out when you take a beer!
  * [ ] Introduce speaker 1.
  * [ ] Take a photo during talk 1.
  * [ ] Introduce speaker 2.
  * [ ] Take a photo during talk 2.
  * [ ] Thank speakers.
  * [ ] Open http://lmorillas.github.io/python_events, "raise hands who is going".
  * [ ] "We need talks: beginners welcome! web, mobile, desktop, embedded, big data, everything goes!"
  * [ ] "We need sponsors: give back to the community!"
  * [ ] "Provisional date for next meetup, raise hands".
  * [ ] "Raise hands who is looking for work? Stand up who is hiring? Mingle!"

# Follow up

* [ ] Post photos to https://www.meetup.com/Ljubljana-Python-Group/
* [ ] Tweet best photo with @python_lj account, something like:
    ```
    Good times yesterday at #ljubljana #python #meetup! <LINK TO MEETUP.COM EVENT HERE>
    ```

**Comment by jurecuhalev** [comment]
@zupo I created the issue, so I could comment with updated talk description.

Title: What I learned from while rewriting Val 202 from Wordpress to Django and Ember.js

With a recent redesign Val 202 is now a single page application. This talk will present infrastructure of syncing Wordpress data with Django and how Django REST frameworks made it easy. The goal of the talk is to discuss pitfalls of decoupled infrastructure and all the different ways that you can fail. 

Jure Čuhalev is a freelance full stack web developer.

**Comment by zupo** [comment]
Great, thanks!

**Comment by zupo** [comment]
@zejn: IIRC you said you can be the second speaker for this meetup?

**Comment by zupo** [comment]
Venue will be Hekovnik this time! Same address, just upstairs of Poligon. 7pm, as always.

**Comment by zupo** [comment]
@termitnjak stepped up to sponsor the event!

**Comment by domenkozar** [comment]
cc @lukapusic

**Comment by zupo** [comment]
We need one more speaker!

**Comment by jurecuhalev** [comment]
As discussed with @zupo, I'll do the talk at one of the future meetups.

**Comment by zupo** [comment]
Due to the very low amount of RSVPs, this meetup has been canceled! See you all in 2018!
