### ISSUE TITLE
June 2018

### ISSUE THREAD

**Issue by zupo** [ljpy/meetups#13]
# Schedule the meetup

* [x] Talk with Marko from Poligon and choose a date/time when their venue is available. Standard time is Thursday at 7pm, but we don't mind some variation. Book it.
* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/ and use the `Schedule a new Meetup` link to schedule a new meetup.
    * [x] Enter `<Month> <Year>` as `What should we do?`
    * [x] Enter `More details:`. Template:
        ```
        Hi fellow Pythonistas!

        The next Python Meetup will take place on <DAY> <DATE HERE>, at <TIME HERE> in Poligon.

        Speakers: post a comment to https://github.com/ljpy/meetups/issues/1 or send an email to ljpy-organizers@googlegroups.com. First two people to do so get to share their ideas/tips/hacks/rants!

        Sponsors: post a comment to https://github.com/ljpy/meetups/issues/2 or send an email to ljpy-organizers@googlegroups.com. First one to do so gets to be the sponsor!


        See you soon!
        ```
    * [x] Select the booked date and time for the meetup.
    * [x] Select `Poligon` as location.
    * [x] When done click `Announce` so members of the user group are notified by email about the upcoming meetup.

# Announce the meetup

Wait a few days. If there are no sponsors and/or speakers that have stepped up, you will have to manually poke them to do so. Go through the list of potential [talks](https://github.com/ljpy/meetups/issues/1) and [sponsors](https://github.com/ljpy/meetups/issues/1). For speakers and sponsors, the rule is First-Come-First-Served: whoever comments on #1 or #2 first, gets to be the speaker/sponsor. Once you have a sponsor and two talks, continue with:

* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/, click on the upcoming meetup and post the following:
    ```
    Dear Python people of Ljubljana and beyond!

    We are glad to announce the speakers and sponsors for the upcoming Python meetup that will happen on <DAY> <DATE HERE>, at <TIME HERE> in Poligon!

    Talks:
    
    <SPEAKER NAME AND TALK 1 TITLE HERE>

    <SPEAKER NAME AND TALK 2 TITLE HERE>

    After the talks you are welcome to stay around and participate in random discussions with fellow attendees. Free beer will be provided by <SPONSOR NAME HERE>!

    More info and RSVP on <LINK TO MEETUP.COM EVENT HERE>.


    See you there!
    ```
* [x] Post announcement to https://www.facebook.com/groups/242976319229784/, https://www.facebook.com/groups/522926241218467/, https://www.facebook.com/groups/slotechstud/, https://www.facebook.com/groups/158003467603274/, https://www.facebook.com/groups/6884481293/, https://www.facebook.com/groups/353060628229741, https://www.facebook.com/groups/165720846803088.
* [x] Submit the event to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_event
* [x] Tweet with @python_lj account:
    ```
    Next #python #meetup in #ljubljana coming soon! <LINK TO MEETUP.COM EVENT HERE>
    ```

# Narrate the meetup

* [ ] Come to Poligon 20 minutes before the start of the meetup.
* [ ] Open up the Meetup.com event page on the projector so that new people know they are in the right place.
* [ ] Decide on a provisional date for next meetup.
* [ ] Ask each speaker for a sentence or two about who they are and what they do. Tell them you need this so you can introduce them.
* [ ] Coordinate with speakers who will go first.
* [ ] If the sponsor is attending, ask them to prepare a 3 minute pitch about what they do and (potentially) who they are looking for.
* [ ] The schedule is normally something along these lines. Feel free to improvise:
  * [ ] "Raise hand if you are new to this meetup".
  * [ ] "Raise hand if you are new to Python".
  * [ ] Introduce the sponsor and give them 3 minutes for their pitch.
  * [ ] Cross out when you take a beer!
  * [ ] Introduce speaker 1.
  * [ ] Take a photo during talk 1.
  * [ ] Introduce speaker 2.
  * [ ] Take a photo during talk 2.
  * [ ] Thank speakers.
  * [ ] Open http://lmorillas.github.io/python_events, "raise hands who is going".
  * [ ] "We need talks: beginners welcome! web, mobile, desktop, embedded, big data, everything goes!"
  * [ ] "We need sponsors: give back to the community!"
  * [ ] "Provisional date for next meetup, raise hands".
  * [ ] "Raise hands who is looking for work? Stand up who is hiring? Mingle!"

# Follow up

* [ ] Post photos to https://www.meetup.com/Ljubljana-Python-Group/
* [ ] Tweet best photo with @python_lj account, something like:
    ```
    Good times yesterday at #ljubljana #python #meetup! <LINK TO MEETUP.COM EVENT HERE>
    ```
* [ ] Verify that the sponsor received invoice from Poligon.

**Comment by zupo** [comment]
Provisional dates 11. to 14. June. Waiting for confirmation.

**Comment by josthkko** [comment]
@zupo I'm talking with Zemanta about 24.May, so this might be kind of close together

**Comment by zupo** [comment]
OK, I'll postpone if it does happen on 24. May, let me know how it goes!

**Comment by plamut** [comment]
24th is reaaally tight for me to prepare a quality talk, 11th or 14th JUN would have suited me much better.

If you cannot find a second speaker for the upcoming meetup, I _might_ be able to jump in, but I cannot promise anything yet at this point.

**Comment by zupo** [comment]
I've talked with Domen and we came up with the idea to join the Lambdas (functional programming) meetup with the Python meetup. And since he's only in LJ till 15. June we gotta have the meetup before. I've asked Poligon for Thursday, 14th June, waiting for confirmation.

I know this is only 14 days after the May meetup, but surely the more the better?

**Comment by josthkko** [comment]
I think we can try with the more the better here for sure :) especially if we join them

**Comment by zupo** [comment]
Date confirmed, 14th June at Poligon.

**Comment by zupo** [comment]
First talk, by @domenkozar: Why types matter
Second talk, by @zupo: Pipenv: Python Dev Workflow for Humans

**Comment by domenkozar** [comment]
Prepare the tomatoes :)

**Comment by josthkko** [comment]
@zupo you will handle everything around this event, right?

**Comment by zupo** [comment]
@josthkko: yes! 

That said, since I'll be one of the speakers, could you possibly do the narrating?

**Comment by josthkko** [comment]
@zupo Would love to, but I won't be around that day.. :(

**Comment by romunov** [comment]
If you're (still) looking for a n00b narrator, I could give it a go.

**Comment by zupo** [comment]
Perfect, be there 15 minutes before please!

**Comment by romunov** [comment]
My suggestion for next time would be to record/stream live. This should be communicated to the presenters in advance so that they have a chance to remove any unauthorized media from their slides. I understand @zupo has much of the equipment ready?

**Comment by zupo** [comment]
Yep, I built a simple rig that combines the perfectly-good-enough-video from a smartphone with a professional-grade shotgun microphone and it works great: https://blog.niteo.co/recording-talks/

**Comment by zupo** [comment]
@romunov: Please send me photos to first.last@gmail.com so I can post to Twitter.

**Comment by zupo** [comment]
Photos still pending, but the rest is done.

**Comment by romunov** [comment]
I was sure I sent them. Anyhu, you've got mail.

**Comment by romunov** [comment]
Hum, maybe this was the reason?

![capture](https://user-images.githubusercontent.com/544571/42493753-7b443c7c-841e-11e8-8645-46f07d2a1de6.JPG)

**Comment by zupo** [comment]
replace `first` & `last` with my first & last names :)

**Comment by romunov** [comment]
🤦‍♂️
