### ISSUE TITLE
February 2019

### ISSUE THREAD

**Issue by romunov** [ljpy/meetups#22]
# Schedule the meetup

* [x] Talk with Poligon and choose a date/time when their venue is available. Standard time is Thursday at 7pm to 9pm, but we don't mind some variation. Book it.
* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/ and use the `Schedule a new Meetup` link to schedule a new meetup.
    * [x] Enter `LjPyMeetup <Month> <Year>` for `Meetup title`
    * [x] Select the booked date and time for the meetup.
    * [x] Select `Poligon` for Where.
    * [x] Enter `Description`. Template:
        ```
        Hello, fellow Pythonistas!

        The next Python Meetup will take place on Thursday 15th November, at 7 pm in Poligon.

        Speakers: post a comment to https://github.com/ljpy/meetups/issues/19 or send an email to ljpy-organizers@googlegroups.com. The first two people to do so get to share their ideas/tips/hacks/rants!

        Sponsors: post a comment to https://github.com/ljpy/meetups/issues/19 or send an email to ljpy-organizers@googlegroups.com. The first one to do so gets to be the sponsor!


        See you soon!
        ```
    * [X] When done click `Publish` and then `Announce it now` so members of the user group are notified by email about the upcoming meetup.

# Announce the meetup

Wait a few days. If there are no sponsors and/or speakers that have stepped up, you will have to manually poke them to do so. Go through the list of potential [talks](https://github.com/ljpy/meetups/issues/1) and [sponsors](https://github.com/ljpy/meetups/issues/1). For speakers and sponsors, the rule is First-Come-First-Served: whoever comments on #1 or #2 first, gets to be the speaker/sponsor. Once you have a sponsor and two talks, continue with:

* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/, click on the upcoming meetup and post the following:
    ```
    Dear Python people of Ljubljana and beyond!

    We are glad to announce the speakers and sponsors for the upcoming Python meetup that will happen on <DAY> <DATE HERE>, at <TIME HERE> in Poligon!

    Talks:
    
    <SPEAKER NAME AND TALK 1 TITLE HERE>

    <SPEAKER NAME AND TALK 2 TITLE HERE>

    After the talks you are welcome to stay around and participate in random discussions with fellow attendees. Free beer will be provided by <SPONSOR NAME HERE>!

    More info and RSVP on <LINK TO MEETUP.COM EVENT HERE>.


    See you there!
    ```
* [x] Post announcement to https://www.facebook.com/groups/242976319229784/, https://www.facebook.com/groups/522926241218467/, https://www.facebook.com/groups/slotechstud/, https://www.facebook.com/groups/158003467603274/, https://www.facebook.com/groups/6884481293/, https://www.facebook.com/groups/353060628229741, https://www.facebook.com/groups/165720846803088.
* [ ] Submit the event to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_event
* [ ] Tweet with @python_lj account:
    ```
    Next #python #meetup in #ljubljana coming soon! <LINK TO MEETUP.COM EVENT HERE>
    ```

# Narrate the meetup

* [x] Come to Poligon 20 minutes before the start of the meetup.
* [x] Open up the Meetup.com event page on the projector so that new people know they are in the right place.
* [x] Decide on a provisional date for next meetup.
* [x] Ask each speaker for a sentence or two about who they are and what they do. Tell them you need this so you can introduce them.
* [x] Coordinate with speakers who will go first.
* [x] If the sponsor is attending, ask them to prepare a 3 minute pitch about what they do and (potentially) who they are looking for.
* [x] The schedule is normally something along these lines. Feel free to improvise:
  * [x] "Raise hand if you are new to this meetup".
  * [x] "Raise hand if you are new to Python".
  * [x] Introduce the sponsor and give them 3 minutes for their pitch.
  * [x] Cross out when you take a beer!
  * [x] Introduce speaker 1.
  * [x] Take a photo during talk 1.
  * [x] Introduce speaker 2.
  * [x] Take a photo during talk 2.
  * [x] Thank speakers.
  * [x] Open http://lmorillas.github.io/python_events, "raise hands who is going".
  * [x] "We need talks: beginners welcome! web, mobile, desktop, embedded, big data, everything goes!"
  * [x] "We need sponsors: give back to the community!"
  * [x] "Provisional date for next meetup, raise hands".
  * [x] "Raise hands who is looking for work? Stand up who is hiring? Mingle!"

# Follow up

* [x] Post photos to https://www.meetup.com/Ljubljana-Python-Group/
* [ ] Tweet best photo with @python_lj account, something like:
    ```
    Good times yesterday at #ljubljana #python #meetup! <LINK TO MEETUP.COM EVENT HERE>
    ```
* [x] Verify that the sponsor received invoice from Poligon.

**Comment by friedcell** [comment]
I can do a talk on [SCRAM](https://en.wikipedia.org/wiki/Salted_Challenge_Response_Authentication_Mechanism) (python on server & javascript in browser).

**Comment by sarajaksa** [comment]
I can do the talk as (sort of) extension on my lightning talk in December. It is going to be a more detailed tutorial on the agent based modeling in python with mesa package. I am going to either do how disgust is connected to political identities or gender differences based on interests and agreeableness and how this affect career choices.

**Comment by romunov** [comment]
Talks (20 minutes):
* @friedcell Talk on SCRAM
* @sarajaksa Agent based modeling in python using mesa package

Lightning talks (5 minutes):
_waiting on entries_
* ~~@jerneju GeoPandas~~
* @gandalfar Superlance for supervisord
* ~~@balavec Running Django on Docker~~

**Comment by jerneju** [comment]
Lightning talk about **GeoPandas**.

**Comment by jurecuhalev** [comment]
✋  Lightning talk with title: "Superlance for supervisord"

**Comment by codehutlabs** [comment]
Lightning talk with the title: "Running Django on Docker"

**Comment by balavec** [comment]
Lightning talk with the title: "Running Django on Docker"

**Comment by romunov** [comment]
Oh nice, looking forward to this. I may have a few questions. :)

**Comment by codehutlabs** [comment]
Cool. Hints welcome.

**Comment by balavec** [comment]
Cool. Hints welcome.

**Comment by balavec** [comment]
@romunov na žalost moram odpovedati za februar. So ravno počitnice tisti teden :(

**Comment by romunov** [comment]
Ni problema! @balavec

**Comment by romunov** [comment]
@zupo can you announce this month's meetup to the facebook groups as outlined in the first message of this issue?

**Comment by jurecuhalev** [comment]
@romunov my slides for today: https://www.dropbox.com/s/9331jkp6dczeemv/SupervisordLightningTalk.pdf?dl=0

**Comment by romunov** [comment]
New to meetups: 5
New to python: 0

**Comment by sarajaksa** [comment]
Moja današnja prezentacija: https://github.com/sarajaksa/DataAnalysis/blob/master/Segregation%20of%20People%20into%20Like-Minded%20Groups%20%5BPython%20MeetUp%20Ljubljana%20February%202019%5D.ipynb

**Comment by romunov** [comment]
@zupo can you amend #1 with the above talks?
Can you amend klev.io in #2 from potential to realized?

**Comment by romunov** [comment]
@friedcell are your slides public? Can you share the repo you talked about?

**Comment by zupo** [comment]
@romunov: you should now have permissions to do so yourself.
