### ISSUE TITLE
March 2019

### ISSUE THREAD

**Issue by romunov** [ljpy/meetups#23]
# Schedule the meetup

* [x] Talk with Poligon and choose a date/time when their venue is available. Standard time is Thursday at 7pm to 9pm, but we don't mind some variation. Book it.
* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/ and use the `Schedule a new Meetup` link to schedule a new meetup.
    * [x] Enter `LjPyMeetup <Month> <Year>` for `Meetup title`
    * [x] Select the booked date and time for the meetup.
    * [x] Select `Poligon` for Where.
    * [x] Enter `Description`. Template:
        ```
        Hello, fellow Pythonistas!

        The next Python Meetup will take place on Thursday 15th November, at 7 pm in Poligon.

        Speakers: post a comment to https://github.com/ljpy/meetups/issues/19 or send an email to ljpy-organizers@googlegroups.com. The first two people to do so get to share their ideas/tips/hacks/rants!

        Sponsors: post a comment to https://github.com/ljpy/meetups/issues/19 or send an email to ljpy-organizers@googlegroups.com. The first one to do so gets to be the sponsor!


        See you soon!
        ```
    * [x] When done click `Publish` and then `Announce it now` so members of the user group are notified by email about the upcoming meetup.

# Announce the meetup

Wait a few days. If there are no sponsors and/or speakers that have stepped up, you will have to manually poke them to do so. Go through the list of potential [talks](https://github.com/ljpy/meetups/issues/1) and [sponsors](https://github.com/ljpy/meetups/issues/1). For speakers and sponsors, the rule is First-Come-First-Served: whoever comments on #1 or #2 first, gets to be the speaker/sponsor. Once you have a sponsor and two talks, continue with:

* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/, click on the upcoming meetup and post the following:
    ```
    Dear Python people of Ljubljana and beyond!

    We are glad to announce the speakers and sponsors for the upcoming Python meetup that will happen on <DAY> <DATE HERE>, at <TIME HERE> in Poligon!

    Talks:
    
    <SPEAKER NAME AND TALK 1 TITLE HERE>

    <SPEAKER NAME AND TALK 2 TITLE HERE>

    After the talks you are welcome to stay around and participate in random discussions with fellow attendees. Free beer will be provided by <SPONSOR NAME HERE>!

    More info and RSVP on <LINK TO MEETUP.COM EVENT HERE>.


    See you there!
    ```
* [x] Post announcement to https://www.facebook.com/groups/242976319229784/, https://www.facebook.com/groups/522926241218467/, https://www.facebook.com/groups/slotechstud/, https://www.facebook.com/groups/158003467603274/, https://www.facebook.com/groups/6884481293/, https://www.facebook.com/groups/353060628229741, https://www.facebook.com/groups/165720846803088.
* [ ] Submit the event to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_event
* [x] Tweet with @python_lj account:
    ```
    Next #python #meetup in #ljubljana coming soon! <LINK TO MEETUP.COM EVENT HERE>
    ```

# Narrate the meetup

* [x] Come to Poligon 20 minutes before the start of the meetup.
* [x] Open up the Meetup.com event page on the projector so that new people know they are in the right place.
* [x] Decide on a provisional date for next meetup.
* [x] Ask each speaker for a sentence or two about who they are and what they do. Tell them you need this so you can introduce them.
* [x] Coordinate with speakers who will go first.
* [x] If the sponsor is attending, ask them to prepare a 3 minute pitch about what they do and (potentially) who they are looking for.
* [x] The schedule is normally something along these lines. Feel free to improvise:
  * [x] "Raise hand if you are new to this meetup".
  * [x] "Raise hand if you are new to Python".
  * [x] Introduce the sponsor and give them 3 minutes for their pitch.
  * [x] Cross out when you take a beer!
  * [x] Introduce speaker 1.
  * [x] Take a photo during talk 1.
  * [x] Introduce speaker 2.
  * [x] Take a photo during talk 2.
  * [x] Thank speakers.
  * [x] Open http://lmorillas.github.io/python_events, "raise hands who is going".
  * [x] "We need talks: beginners welcome! web, mobile, desktop, embedded, big data, everything goes!"
  * [x] "We need sponsors: give back to the community!"
  * [x] "Provisional date for next meetup, raise hands".
  * [x] "Raise hands who is looking for work? Stand up who is hiring? Mingle!"

# Follow up

* [x] Post photos to https://www.meetup.com/Ljubljana-Python-Group/
* [ ] Tweet best photo with @python_lj account, something like:
    ```
    Good times yesterday at #ljubljana #python #meetup! <LINK TO MEETUP.COM EVENT HERE>
    ```
* [x] Verify that the sponsor received invoice from Poligon.

**Comment by romunov** [comment]
It has been suggested to have a meeting on Tuesday, March 19th. We are in the process of booking the spot. Please hold.

If you would like to sponsor the event and give something back to the community, please contact me.

**Comment by romunov** [comment]
2019-03-19 datum is confirmed. Please mark your calendars.

**Comment by kavselj** [comment]
Lightning talk about **Magic the Gathering**.

**Comment by romunov** [comment]
Scheduled talks:

Regular talk(s) (~20 minutes):
* @drorspei JupyterLab
* @miqwit Image matching via fingerprinting

Lightning talks (5 minutes):
* @kavselj Magic the Gathering
* @balavec Running Django on Docker
* @romunov Static websites are (still) the rage - Pelican static page generator ([slides](https://docs.google.com/presentation/d/1-61-3hebyWacIqG3z-zYT9d6Zev-GWSBeLWPgfzhjPs/edit?usp=sharing))

**Comment by drorspei** [comment]
I can give a regular talk on **JupyterLab**.

**Comment by romunov** [comment]
Really looking forward to hearing about this. I use Jupyter Notebooks all the time but haven't had the chance to switch over to JupyterLab. This may just be the push I need? :)

**Comment by romunov** [comment]
@jerneju how is that GeoPandas lightning talk coming along?

**Comment by inejc** [comment]
Hey @romunov, I'm thinking of preparing a lightning talk about a Scala port of scikit-learn that I've been working on. I'm unsure, however, whether it would be a good fit for a Python meetup. Thoughts?

**Comment by miqwit** [comment]
I can contribute to a regular talk on image matching via fingerprinting, a python library I used extensively (and contributing). I would give details on how images are fingerprinted, how they are stored and how to retrieve them very quickly among millions. Is there any available slot?

**Comment by romunov** [comment]
Sold, to the man in first row (@miqwit)!

**Comment by romunov** [comment]
@zupo  please advertise this event on social media.

**Comment by miqwit** [comment]
> Sold, to the man in first row (@miqwit)!

Thanks @romunov, will work on it :)

**Comment by drorspei** [comment]
Hi Hi
I just got booked a flight at 20:50 for work :( Will I be able to start the talk before 18:30, so that I can leave by 19:00?

**Comment by romunov** [comment]
We start at 18:00, a few minutes for intro and sponsor pitch and then you're up. You should have plenty of time. Too bad you won't be able to stick around afterwards.

@drorspei

**Comment by drorspei** [comment]
@romunov Cool, thanks :)

**Comment by kavselj** [comment]
https://docs.google.com/presentation/d/161spaedE_c_b-u78M4poUCkrst_dtCGc73fAEbwT_u0/edit?usp=drivesdk

My Magic: The Gathering lightning talk.

**Comment by drorspei** [comment]
Hi hi
Thanks for having me today, it was lots of fun!
Next time I'll even stay to the end :)
