### ISSUE TITLE
April 2019

### ISSUE THREAD

**Issue by romunov** [ljpy/meetups#25]
# Schedule the meetup

* [x] Talk with Poligon and choose a date/time when their venue is available. Standard time is Thursday at 7pm to 9pm, but we don't mind some variation. Book it.
* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/ and use the `Schedule a new Meetup` link to schedule a new meetup.
    * [x] Enter `LjPyMeetup <Month> <Year>` for `Meetup title`
    * [x] Select the booked date and time for the meetup.
    * [x] Select `Poligon` for Where.
    * [x] Enter `Description`. Template:
        ```
        Hello, fellow Pythonistas!

        The next Python Meetup will take place on Wednesday 24th of April, at 6 pm in Poligon (Tobačna).

        Speakers: post a comment to https://github.com/ljpy/meetups/issues/25 or send an email to ljpy-organizers@googlegroups.com. The first two people to do so get to share their ideas/tips/hacks/rants!

        Sponsors: post a comment to https://github.com/ljpy/meetups/issues/25 or send an email to ljpy-organizers@googlegroups.com. The first one to do so gets to be the sponsor!


        See you soon!
        ```
    * [x] When done click `Publish` and then `Announce it now` so members of the user group are notified by email about the upcoming meetup.

# Announce the meetup

Wait a few days. If there are no sponsors and/or speakers that have stepped up, you will have to manually poke them to do so. Go through the list of potential [talks](https://github.com/ljpy/meetups/issues/1) and [sponsors](https://github.com/ljpy/meetups/issues/1). For speakers and sponsors, the rule is First-Come-First-Served: whoever comments on #1 or #2 first, gets to be the speaker/sponsor. Once you have a sponsor and two talks, continue with:

* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/, click on the upcoming meetup and post the following:
    ```
    Dear Python people of Ljubljana and beyond!

    We are glad to announce the speakers and sponsors for the upcoming Python meetup that will happen on <DAY> <DATE HERE>, at <TIME HERE> in Poligon!

    Talks:
    
    <SPEAKER NAME AND TALK 1 TITLE HERE>

    <SPEAKER NAME AND TALK 2 TITLE HERE>

    After the talks you are welcome to stay around and participate in random discussions with fellow attendees. Free beer will be provided by <SPONSOR NAME HERE>!

    More info and RSVP on <LINK TO MEETUP.COM EVENT HERE>.


    See you there!
    ```
* [x] Post announcement to https://www.facebook.com/groups/242976319229784/, https://www.facebook.com/groups/522926241218467/, https://www.facebook.com/groups/slotechstud/, https://www.facebook.com/groups/158003467603274/, https://www.facebook.com/groups/6884481293/, https://www.facebook.com/groups/353060628229741, https://www.facebook.com/groups/165720846803088.
* [ ] Submit the event to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_event
* [x] Tweet with @python_lj account:
    ```
    Next #python #meetup in #ljubljana coming soon! <LINK TO MEETUP.COM EVENT HERE>
    ```

# Narrate the meetup

* [x] Come to Poligon 20 minutes before the start of the meetup.
* [x] Open up the Meetup.com event page on the projector so that new people know they are in the right place.
* [x] Decide on a provisional date for next meetup.
* [x] Ask each speaker for a sentence or two about who they are and what they do. Tell them you need this so you can introduce them.
* [x] Coordinate with speakers who will go first.
* [x] If the sponsor is attending, ask them to prepare a 3 minute pitch about what they do and (potentially) who they are looking for.
* [x] The schedule is normally something along these lines. Feel free to improvise:
  * [x] "Raise hand if you are new to this meetup".
  * [x] "Raise hand if you are new to Python".
  * [x] Introduce the sponsor and give them 3 minutes for their pitch.
  * [x] Cross out when you take a beer!
  * [x] Introduce speaker 1.
  * [x] Take a photo during talk 1.
  * [x] Introduce speaker 2.
  * [x] Take a photo during talk 2.
  * [x] Thank speakers.
  * [x] Open http://lmorillas.github.io/python_events, "raise hands who is going".
  * [x] "We need talks: beginners welcome! web, mobile, desktop, embedded, big data, everything goes!"
  * [x] "We need sponsors: give back to the community!"
  * [x] "Provisional date for next meetup, raise hands".
  * [x] "Raise hands who is looking for work? Stand up who is hiring? Mingle!"

# Follow up

* [x] Post photos to https://www.meetup.com/Ljubljana-Python-Group/
* [ ] Tweet best photo with @python_lj account, something like:
    ```
    Good times yesterday at #ljubljana #python #meetup! <LINK TO MEETUP.COM EVENT HERE>
    ```
* [x] Verify that the sponsor received invoice from Poligon.

**Comment by romunov** [comment]
April's meetup is on 24th of April. That's a Wednesday in case you were wondering. We are meeting at 18 hundred hours (6 pm) in Poligon.

Talks:
* @drola Serverless Jupyter
* slot vacant

Lightning talks:
* @CimeM Parallel Python jobs with Kubernetes
* @sarajaksa What I wished I knew about python conferences before I attended my first one
* ~@BuiltForThis  classmate Mushroom world~
* @gandalfar Why Hanging out in Slack/IRC/Discord will level up your dev skills
* @AleksMat Documenting REST API with Flask-RESTPlus and marshmallow

Sponsor:
* hehe.si

**Comment by romunov** [comment]
Happy to take in a sponsor for April 2019.

**Comment by CimeM** [comment]
Lightning talk, titled: "Parallel Python jobs with Kubernetes" ⚓️

**Comment by sarajaksa** [comment]
I will apply for my lightning talk: What I wished I knew about python conferences before I attended my first one
Blog post for this talk: https://sarajaksa.eu/2019/04/you-will-learn-a-lot-and-you-will-meet-a-lot-of-people-python-meetup-ljubljana-april-2019/

And @romunov, I did the homework you gave me (partly), so my classmate from the last time will also have a lightning talk titled: Mushroom world

**Comment by romunov** [comment]
Splendid news!

**Comment by romunov** [comment]
April's sponsor is a first-timer [hehe d.o.o.](https://www.hehe.si/) (@idioterna).

**Comment by drola** [comment]
I could have a talk about Serverless Jupyter.
Behind the scenes, it's actually a use case of WebAssembly enabled by Emscripten and Pyodide. Jupyter notebooks running in a browser make the whole issue of containerizing and isolating Python kernels on servers obsolete. I also expect a new class of apps for in-browser data analysis. Google Sheets and Office365 Excel will be able to use Python as a macro language.

The topic is highly interesting. But due to the short timeline, I would mostly recycle content from my previous WebAssembly talk from JSDayES ( https://wasm.drola.si/slides/#/ ) and blog posts from Mozilla ( https://hacks.mozilla.org/2019/04/pyodide-bringing-the-scientific-python-stack-to-the-browser/ ).

**Comment by romunov** [comment]
Looking forward to it! Would this be a 20' talk? @drola

**Comment by drola** [comment]
This would be a 20' talk.

**Comment by romunov** [comment]
Perfect, thank you!

**Comment by jurecuhalev** [comment]
Slides for my lightning talk: https://www.dropbox.com/s/khya0ktds6ul9sl/ChatAppsLightningTalks.pdf?dl=0

**Comment by BuiltForThis** [comment]
Hey, letting you guys know the MushroomWorld talk (by me) can't happen, because the meetup overlaps with my SQL seminar. Sorry about that, I'm hoping to give a longer than 5' talk on the next meetup. Good luck guys!

**Comment by drola** [comment]
@romunov, does the projector have HDMI or mDP input?

**Comment by CimeM** [comment]
My slides: https://docs.google.com/presentation/d/13FW-j2kEulDkrXxBBySwUg_NH8aD1KPjyL63AlR7x0I/edit?usp=sharing

**Comment by romunov** [comment]
@drola there are HDMI and D-SUB jacks ready.

@BuiltForThis next time then, thanks anyway.

**Comment by AleksMat** [comment]
@romunov
I managed to prepare a lightning talk about "Documenting REST API with Flask-RESTPlus and marshmallow". Sorry for late notice, but I didn't know if I will have enough time for this.

I hope I can still have it this time, otherwise next time would also be fine. I can show it from my laptop, HDMI should work.

**Comment by romunov** [comment]
@AleksMat Deal! See you in an hour.

**Comment by drola** [comment]
Serverless Jupyter slides: https://drive.google.com/open?id=1uRS9askiukTpovFl_2KYArdxl6QWS8vU

**Comment by romunov** [comment]
Number of people tagged as attending on Meetup: 43
Number of people actually attending: 30
Weather: cloudy
