### ISSUE TITLE
June 2017

### ISSUE THREAD

**Issue by zupo** [ljpy/meetups#3]
# Schedule the meetup

* [x] Talk with Marko from Poligon and choose a date/time when their venue is available. Standard time is Thursday at 7pm, but we don't mind some variation. Book it.
* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/ and use the `Schedule a new Meetup` link to schedule a new meetup.
  * [x] Enter `<Month> <Year>` as `What should we do?`
  * [x] Enter `More details:`. Template:
    ```
    Hi fellow Pythonistas!

    The next Python Meetup will take place on <DATE HERE>, at <TIME HERE> in Poligon.

    Speakers: post a comment to https://github.com/ljpy/meetups/issues/1 or send an email to ljpy-organizers@googlegroups.com. First two people to do so get to share their ideas/tips/hacks/rants!

    Sponsors: post a comment to https://github.com/ljpy/meetups/issues/2 or send an email to ljpy-organizers@googlegroups.com. First one to do so gets to be the sponsor!


    See you soon!
    ```
  * [x] Select the booked date and time for the meetup.
  * [x] Select `Poligon` as location.
  * [x] When done click `Announce` so members of the user group are notified by email about the upcoming meetup.

# Announce the meetup

Wait a few days. If there are no sponsors and/or speakers that have stepped up, you will have to manually poke them to do so. Go through the list of potential [talks](https://github.com/ljpy/meetups/issues/1) and [sponsors](https://github.com/ljpy/meetups/issues/1). For speakers and sponsors, the rule is First-Come-First-Served: whoever comments on #1 or #2 first, gets to be the speaker/sponsor. Once you have a sponsor and two talks, continue with:

* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/, click on the upcoming meetup and post the following:
  ```
  Dear Python people of Ljubljana and beyond!

  We are glad to announce the speakers and sponsors for the upcoming Python meetup that will happen on <DATE HERE>, at <TIME HERE> in Poligon!

  <SPEAKER NAME AND TALK 1 TITLE HERE>

  <SPEAKER NAME AND TALK 2 TITLE HERE>

  After the talks you are welcome to stay around and participate in random discussions with fellow attendees. Free beer will be provided by <SPONSOR NAME HERE>!

  More info and RSVP on <LINK TO MEETUP.COM EVENT HERE>.


  See you there!
  ```
* [x] Post announcement to https://www.facebook.com/groups/242976319229784/, https://www.facebook.com/groups/522926241218467/, https://www.facebook.com/groups/slotechstud/, https://www.facebook.com/groups/158003467603274/, https://www.facebook.com/groups/6884481293/, https://www.facebook.com/groups/353060628229741, https://www.facebook.com/groups/165720846803088.
* [x] Submit the event to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_event
* [x] Post a news item on slo-tech.com. (login, click `pošlji novico`)
* [x] Post an announcement to http://www.internetmojster.com/novice/.
* [x] Tweet with @python_lj account:
```
Next #python #meetup in #ljubljana coming soon! <LINK TO MEETUP.COM EVENT HERE>
```

# Narrate the meetup

* [x] Come to Poligon 20 minutes before the start of the meetup.
* [x] Open up the Meetup.com event page on the projector so that new people know they are in the right place.
* [x] Decide on a provisional date for next meetup.
* [x] Ask each speaker for a sentence or two about who they are and what they do. Tell them you need this so you can introduce them.
* [x] Coordinate with speakers who will go first.
* [x] If the sponsor is attending, ask them to prepare a 3 minute pitch about what they do and (potentially) who they are looking for.
* [x] The schedule is normally something along these lines. Feel free to improvise:
  * [x] "Any international guests"? If yes, ask speakers to present in English if possible.
  * [x] "Please use #ljpy hashtag on social networks for shoutouts, comments, photos, etc.".
  * [x] "Raise hand if you are new to this meetup".
  * [x] "Raise hand if you are new to Python".
  * [x] Introduce the sponsor and give them 3 minutes for their pitch.
  * [x] Introduce speaker 1.
  * [x] Take a photo during talk 1.
  * [x] Introduce speaker 2.
  * [x] Take a photo during talk 2.
  * [x] Thank speakers.
  * [x] Open http://lmorillas.github.io/python_events, "raise hands who is going".
  * [x] "We need talks: beginners welcome! web, mobile, desktop, embedded, big data, everything goes!"
  * [x] "We need sponsors: give back to the community!"
  * [x] "Provisional date for next meetup, raise hands".
  * [x] "Raise hands who is looking for work? Stand up who is hiring? Mingle!"

# Follow up

* [x] Post photos to https://www.meetup.com/Ljubljana-Python-Group/
* [x] Tweet best photo with @python_lj account, something like:
  ```
  Good times yesterday at #ljubljana #python #meetup! <LINK TO MEETUP.COM EVENT HERE>
  ```
* [x] Verify that the sponsor received invoice from Poligon.

**Comment by zupo** [comment]
@jmakov stepped up to do a "Technical debt - how to measure it and best practices" talk and arrange sponsorship from Bitstamp. 

We need one more talk!

**Comment by jmakov** [comment]
Just for plan B I offer 2 or 3 more talks: 
- Selenium acrobatics and Selenium components
- Writing trading bots for fun and profit
- Getting rich writing your ad clicking bot
- Bot detection systems and strategies to get around them
- SQLAlchemy acrobatics in a distributed system, XA transactions and concurrency issues
- Modern distributed architectures for real time processing/web
- Python logging - best practices
- Scaling horizontally and vertically with Python
- Real time ETL in Python
- Statistical analysis of time series for fun and profit
- Scraping Facebook (since not all data is exposed through public API)
- Using Selenium to win games, organized by your radio station
- PyCharm (or IntelliJ Ultimate) and why you should use it too
- Setting up continuous testing in your project and how it can benefit your team
- Advanced py.test - fixture and test parametrization, test parallelization and checking test isolation
- Demystifying mixins and MRO
- Metaclasses in daily life
- Processes and habits that will enable your team to deliver and grow professionally while dealing with daily fire(s)
- Building CI/CD pipelines with Jenkins Blue Ocean and Jenkinsfiles
- Preventing security regressions with unit testing

**Comment by zupo** [comment]
Marko Limbek stepped up to be the speaker!

**Comment by zupo** [comment]
Marko said he cannot come, so his talk is being replaced by "Merging structured data with jsonmerge" by @avian2.

**Comment by zupo** [comment]
Sorry, but there was a misunderstanding. The replacement talk will be by @andrejburja, about measuring vibrations.

**Comment by zupo** [comment]
Photos: https://www.meetup.com/Ljubljana-Python-Group/photos/27952283/

**Comment by zupo** [comment]
https://twitter.com/python_lj/status/877990559436070912

**Comment by zupo** [comment]
All done, see you on the next meetup!
