### ISSUE TITLE
October 2019

### ISSUE THREAD

**Issue by romunov** [ljpy/meetups#35]
# Schedule the meetup

* [x] Talk with Poligon and choose a date/time when their venue is available. Standard time is Thursday at 7pm to 9pm, but we don't mind some variation. Book it.
* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/ and use the `Schedule a new Meetup` link to schedule a new meetup.
    * [x] Enter `LjPyMeetup <Month> <Year>` for `Meetup title`
    * [x] Select the booked date and time for the meetup.
    * [x] Select `Poligon` for Where.
    * [x] Enter `Description`. Template:
        ```
        Hello, fellow Pythonistas!

        The next Python Meetup will take place on Thursday 15th November, at 7 pm in Poligon.

        Speakers: post a comment to https://github.com/ljpy/meetups/issues/19 or send an email to ljpy-organizers@googlegroups.com. The first two people to do so get to share their ideas/tips/hacks/rants!

        Sponsors: post a comment to https://github.com/ljpy/meetups/issues/19 or send an email to ljpy-organizers@googlegroups.com. The first one to do so gets to be the sponsor!


        See you soon!
        ```
    * [x] When done click `Publish` and then `Announce it now` so members of the user group are notified by email about the upcoming meetup.

# Announce the meetup

Wait a few days. If there are no sponsors and/or speakers that have stepped up, you will have to manually poke them to do so. Go through the list of potential [talks](https://github.com/ljpy/meetups/issues/1) and [sponsors](https://github.com/ljpy/meetups/issues/1). For speakers and sponsors, the rule is First-Come-First-Served: whoever comments on #1 or #2 first, gets to be the speaker/sponsor. Once you have a sponsor and two talks, continue with:

* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/, click on the upcoming meetup and post the following:
    ```
    Dear Python people of Ljubljana and beyond!

    We are glad to announce the speakers and sponsors for the upcoming Python meetup that will happen on <DAY> <DATE HERE>, at <TIME HERE> in Poligon!

    Talks:

    <SPEAKER NAME AND TALK 1 TITLE HERE>

    <SPEAKER NAME AND TALK 2 TITLE HERE>

    After the talks you are welcome to stay around and participate in random discussions with fellow attendees. Free beer will be provided by <SPONSOR NAME HERE>!

    More info and RSVP on <LINK TO MEETUP.COM EVENT HERE>.


    See you there!
    ```
* [x] Post announcement to https://www.facebook.com/groups/242976319229784/, https://www.facebook.com/groups/522926241218467/, https://www.facebook.com/groups/slotechstud/, https://www.facebook.com/groups/158003467603274/, https://www.facebook.com/groups/6884481293/, https://www.facebook.com/groups/353060628229741, https://www.facebook.com/groups/165720846803088.
* [ ] Submit the event to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_event
* [x] Tweet with @python_lj account:
    ```
    Next #python #meetup in #ljubljana coming soon! <LINK TO MEETUP.COM EVENT HERE>
    ```

# Narrate the meetup

* [x] Come to Poligon 20 minutes before the start of the meetup.
* [x] Open up the Meetup.com event page on the projector so that new people know they are in the right place.
* [x] Decide on a provisional date for next meetup.
* [x] Ask each speaker for a sentence or two about who they are and what they do. Tell them you need this so you can introduce them.
* [x] Coordinate with speakers who will go first.
* [x] If the sponsor is attending, ask them to prepare a 3 minute pitch about what they do and (potentially) who they are looking for.
* [x] The schedule is normally something along these lines. Feel free to improvise:
  * [x] "Raise hand if you are new to this meetup".
  * [x] "Raise hand if you are new to Python".
  * [x] Introduce the sponsor and give them 3 minutes for their pitch.
  * [x] Cross out when you take a beer!
  * [x] Introduce speaker 1.
  * [x] Take a photo during talk 1.
  * [x] Record number of attendees, number of RSVPs on meetup.com and weather to github issue for respective month (see #25 for example).
  * [x] Introduce speaker 2.
  * [x] Take a photo during talk 2.
  * [x] Thank speakers.
  * [x] Open http://lmorillas.github.io/python_events, "raise hands who is going".
  * [x] "We need talks: beginners welcome! web, mobile, desktop, embedded, big data, everything goes!"
  * [x] "We need sponsors: give back to the community!"
  * [x] "Provisional date for next meetup, raise hands".
  * [x] "Raise hands who is looking for work? Stand up who is hiring? Mingle!"

# Follow up

* [x] Post photos to https://www.meetup.com/Ljubljana-Python-Group/
* [x] Tweet best photo with @python_lj account, something like:
    ```
    Good times yesterday at #ljubljana #python #meetup! <LINK TO MEETUP.COM EVENT HERE>
    ```
* [x] Verify that the sponsor received invoice from Poligon.

**Comment by romunov** [comment]
Provisional date for the meetup is 2019-10-15. If you feel like you could contribute a regular or lightning talk, drop us a line below.

**Comment by itsadrake** [comment]
Regular talk: Haskell for Python programmers

**Comment by zupo** [comment]
Just got confirmation for the second talk: @ra1u will share some tips about testing (language agnostic).

**Comment by JanLikar** [comment]
Hey guys, could we get a spot at the meetup in October for @johnbaldwin? He's a good public speaker from Boston and an all-round great guy whom I met at the PyCon Balkan conference and is kind enough to offer to come to Slovenia in October to give a talk.  @zupo @romunov

**Comment by JanLikar** [comment]
Also, I'd like to give a lightning talk, if possible.

**Comment by zupo** [comment]
I'm +1. We can have a longer event again, no problem. :) 6PM to 9PM should be enough for 3x 20 minute talks (+questions) and a few lightnings.

**Comment by JozeHladnik** [comment]
As already sheared with Nejc, I would present my challenges with machine vision in Smart farming.
20 min talk.    Accepted?

**Comment by johnbaldwin** [comment]
I can give a talk as short or as long as you want/will fit. For topic ideas:

1. Simplify your API with Django REST Framework viewsets
2. Testing strategies with a focus on Django
3. Django Ask Me Anything, "Stump the new guy" ;)
4. Multi-tenancy with Django
5. Preparing for and giving talks (public speaking strategies to make your audience happy)
6. Other ideas?

**Comment by zupo** [comment]
We can probably squeeze 4 talks in, but 3 is going to be more comfortable. Does anyone wish to rather do it in November? Again, perfectly doable to do 4, asking purely for the slight chance of someone preferring a later date.

@johnbaldwin, @JozeHladnik, @AlexeiDrake, @ra1u ^^

**Comment by zupo** [comment]
@ra1u volunteered to skip this meetup and do his talk at the next. So we have three talks and room for a couple of lightnings!

**Comment by zupo** [comment]
@johnbaldwin: I asked in our Slack group and there is slight preference towards `Simplify your API with Django REST Framework viewsets`, but the sample set if quite tiny so take that with a grain of salt.

UPDATE: more people chipped in now, the `API` title is definitely getting the most votes

**Comment by romunov** [comment]
@JanLikar what will your lightning talk be about?

**Comment by johnbaldwin** [comment]
@zupo Thanks! I will plan to talk about API development if that stays the most popular topic.

There *is* another topic I forgot about when I put together the list above.

### Analyzing the viability (health) of open source projects

One of my friends created this project: https://github.com/okrahealth/okra/blob/master/README.md

* It came out of his Masters in Data Science work at Northeaster University in Boston. 
* We worked on the project at PyCon US 2019 in Cleveland, but haven't made much progress since (note the irony)
* I want to talk briefly about open source project viability and risks
* I think this topic impacts everyone

Curious what you think @zupo 

cc @JanLikar

**Comment by zupo** [comment]
Personally, I'd love to learn more about okra, I battle with such questions a lot. That said, the majority of people will probably relate more to Django + APIs.

**Comment by romunov** [comment]
@johnbaldwin  You can give this talk over some beers and sticky fingers. :)

**Comment by johnbaldwin** [comment]
Will do! APIs for the event. Open source health for beers!

**Comment by JanLikar** [comment]
@romunov, sorry for a late reply, I didn't get the notification.

My talk is going to be about DB transactions and a specific anti-pattern that can hinder DB performance.

The title I used at PyCon Balkan was "Transactions considered harmful".

**Comment by JanLikar** [comment]
@romunov, sorry, I'll have to cancel my lightning talk. I have a majestic headache and am unable to do it.

**Comment by JozeHladnik** [comment]
Hi there, this is my presentation shorturl.at/OU378
Any question or comment welcome at joze.hladnik@kis.si.
Happy growing!   Jože

**Comment by itsadrake** [comment]
Here are my Haskell slides as well. Thanks for attending! http://bit.ly/HaskellPy

**Comment by johnbaldwin** [comment]
Here is the  link to my slides: http://bit.ly/ljubljana-drf-viewsets

Here is a direct link to my demo project: https://github.com/DjangoBoston/mulsite-demo

Thank you for the opportunity to speak. I hope it was helpful. If you have questions or follow up comments, please feel free to email me at jlbaldwin@gmail.com and include "Ljubljana Python" in the subject. 

Lep pozdrav,
-John
