### ISSUE TITLE
Setup LjPyMeetup Youtube channel

### ISSUE THREAD

**Issue by jmakov** [ljpy/meetups#39]
I have an old video of one of my talks (1.6GB) and a few PDF files from other LjPyMeetup talks. Would be great if we had a platform to upload it to.

Or is there a central channel for all Python Meetups? Couldn't find anything on Youtube.

**Comment by zupo** [comment]
I plan to record the December's Meetup, after which I'll have to create the channel. I'll ping you when it's done!

And thanks!

**Comment by romunov** [comment]
https://www.youtube.com/channel/UCN8JxzMuRkYtdEXYD_8vsQA
