### ISSUE TITLE
June 2020

### ISSUE THREAD

**Issue by drorspei** [ljpy/meetups#43]
Want to do an online meetup in April?

Here's a blog post by meetup on having online meetups:
https://www.meetup.com/blog/how-to-host-an-online-event-on-meetup/

**Comment by zupo** [comment]
I can participate but don't have the time or energy to organize, sorry. @romunov?

**Comment by romunov** [comment]
Right now I think our energy can be dissipated in other venues.

**Comment by drorspei** [comment]
Hej hej
Just checking in. What do you think about end of June? 
I've attended a couple of online Berlin pydata meetups that were pretty cool. They had zoom, and presenters shared screen. Also in the last meetup, between two talks they separated people into breakout rooms so we could socialize in small groups.

Whenever we have the next meetup, virtual or not, I'd be happy to do one of the talks.

**Comment by romunov** [comment]
Thanks for offering to do a talk. Right now I can't find energy and time to organize this, but would love it if you (or someone else) took the lead.

**Comment by romunov** [comment]
Just realized I used the same argument (time and energy) as @zupo in March. :facepalm:

**Comment by drorspei** [comment]
Ok! I have time this month. How do I take the lead on this?

**Comment by zupo** [comment]
I'll assign you as "organizer" on Meetup so you can create an event. What's your Meetup username/email?

**Comment by drorspei** [comment]
Yey cool
It's dror.mastershin@gmail.com

**Comment by zupo** [comment]
@drorspei you should have received an invite.

If yes, then follow https://github.com/ljpy/meetups/blob/master/ORGANIZATION.md and customize it as you see fit for an online event.
