### ISSUE TITLE
LjPyMeetup August 2020

### ISSUE THREAD

**Issue by drorspei** [ljpy/meetups#44]
# Schedule the meetup

* [x] ~~Have zoom account for meeting~~
* [x] ~~Go to https://www.meetup.com/Ljubljana-Python-Group/ and use the `Schedule a new Meetup` link to schedule a new meetup.~~
    * [x] ~~Enter `LjPyMeetup <Month> <Year>` for `Meetup title`~~
    * [x] ~~Select the booked date and time for the meetup.~~
    * [x] ~~Select `make online event`.~~
    * [x] ~~Enter `Description`. Template:~~
        ```
        Hello, fellow Pythonistas!

        The next Python Meetup will take place on Thursday 15th November, at 7 pm in Poligon.

        Speakers: post a comment to https://github.com/ljpy/meetups/issues/19 or send an email to ljpy-organizers@googlegroups.com. The first two people to do so get to share their ideas/tips/hacks/rants!

        Sponsors: post a comment to https://github.com/ljpy/meetups/issues/19 or send an email to ljpy-organizers@googlegroups.com. The first one to do so gets to be the sponsor!


        See you soon!
        ```
    * [x] ~~When done click `Publish` and then `Announce it now` so members of the user group are notified by email about the upcoming meetup.~~
* [ ] Compile a list of other online meetups to present during the meetup.

# Announce the meetup

Wait a few days. If there are no sponsors and/or speakers that have stepped up, you will have to manually poke them to do so. Go through the list of potential [talks](https://github.com/ljpy/meetups/issues/1) and [sponsors](https://github.com/ljpy/meetups/issues/1). For speakers and sponsors, the rule is First-Come-First-Served: whoever comments on #1 or #2 first, gets to be the speaker/sponsor. Once you have a sponsor and two talks, continue with:

* [ ] Go to https://www.meetup.com/Ljubljana-Python-Group/, click on the upcoming meetup and post the following:
    ```
    Dear Python people of Ljubljana and beyond!

    We are glad to announce the speakers and sponsors for the upcoming Python meetup that will happen on <DAY> <DATE HERE>, at <TIME HERE> in Poligon!

    Talks:

    <SPEAKER NAME AND TALK 1 TITLE HERE>

    <SPEAKER NAME AND TALK 2 TITLE HERE>

    After the talks you are welcome to stay around and participate in random discussions with fellow attendees. Free beer will be provided by <SPONSOR NAME HERE>!

    More info and RSVP on <LINK TO MEETUP.COM EVENT HERE>.


    See you there!
    ```
* [ ] Post announcement to https://www.facebook.com/groups/242976319229784/, https://www.facebook.com/groups/522926241218467/, https://www.facebook.com/groups/slotechstud/, https://www.facebook.com/groups/158003467603274/, https://www.facebook.com/groups/6884481293/, https://www.facebook.com/groups/353060628229741, https://www.facebook.com/groups/165720846803088.
* [ ] Submit the event to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_event
* [ ] Tweet with @python_lj account:
    ```
    Next #python #meetup in #ljubljana coming soon! <LINK TO MEETUP.COM EVENT HERE>
    ```

# Narrate the meetup

* [ ] Start the meeting 20 minutes before the start of the meetup.
* [ ] Ask each speaker for a sentence or two about who they are and what they do. Tell them you need this so you can introduce them.
* [ ] Coordinate with speakers who will go first.
* [ ] Give speakers share screen privileges.
* [ ] Open up the Meetup.com event page in share screen so that new people know they are in the right place.
* [ ] Decide on a provisional date for next meetup.
* [ ] Start recoding.
* [ ] The schedule is normally something along these lines. Feel free to improvise:
  * [ ] "Raise hand if you are new to this meetup".
  * [ ] "Raise hand if you are new to Python".
  * [ ] Introduce speaker 1.
  * [ ] Take a photo during talk 1.
  * [ ] Introduce speaker 2.
  * [ ] Take a photo during talk 2.
  * [ ] Thank speakers.
  * [ ] Present other virtual meetups list, "raise hands who is going".
  * [ ] "We need talks: beginners welcome! web, mobile, desktop, embedded, big data, everything goes!"
  * [ ] "Provisional date for next meetup, raise hands".
  * [ ] "Raise hands who is looking for work? Stand up who is hiring? Chat!"

# Follow up

* [ ] Post photos to https://www.meetup.com/Ljubljana-Python-Group/
* [ ] Tweet best photo with @python_lj account, something like:
    ```
    Good times yesterday at #ljubljana #python #meetup! <LINK TO MEETUP.COM EVENT HERE>
    ```

**Comment by romunov** [comment]
I can show how I automated my deployment of static pages generated with Pelican (written in Python) using GitHub Actions.

**Comment by drorspei** [comment]
@romunov nice!

**Comment by BorutFlis** [comment]
I would do a lightning talk tommorow.

**Comment by romunov** [comment]
@BorutFlis do you have a title yet?

**Comment by BorutFlis** [comment]
Outlier detection in text-mining

**Comment by drorspei** [comment]
Cools!
I've updated the meetup event ^_^

**Comment by romunov** [comment]
@drorspei you are 8.
