### ISSUE TITLE
September 2020 meetup

### ISSUE THREAD

**Issue by cmdctrlesc** [ljpy/meetups#45]
# Schedule the meetup

- [x] Decide whether this meetup will be a virtual one again or not. Follow national coronavirus guidelines regarding gatherings of 10-50 people. If a live meetup is decided on, contact Računalniški muzej for dates. Standard time is Thursday at 7pm to 9pm, but we don't mind some variation. Book it.
 

- [x]  Go to https://www.meetup.com/Ljubljana-Python-Group/ and use the Schedule a new Meetup link to schedule a new meetup.

 

- [x] Enter LjPyMeetup [Month] [Year] for Meetup title

 

- [x] Select the booked date and time for the meetup.

 

- [x] Select [Venue name/Virtual] for Where.

 

- [x] Enter Description. Template:

> Hello, fellow Pythonistas!
>
>The next Python Meetup will take place on Thursday 15th November, at 7 pm in [Venue/virtual]
>
>Speakers: post a comment to https://github.com/ljpy/meetups/issues/19 or send an email to ljpy->organizers@googlegroups.com. The first two people to do so get to share their ideas/tips/hacks/rants!
>
>Sponsors: post a comment to https://github.com/ljpy/meetups/issues/19 or send an email to ljpy->organizers@googlegroups.com. The first one to do so gets to be the sponsor!
>
>
>See you soon!

- [x] When done click Publish and then Announce it now so members of the user group are notified by email about the upcoming meetup.

 # Announce the meetup

Wait a few days. If there are no sponsors and/or speakers that have stepped up, you will have to manually poke them to do so. Go through the list of potential talks and sponsors. For speakers and sponsors, the rule is First-Come-First-Served: whoever comments on #1 or #2 first, gets to be the speaker/sponsor. Once you have a sponsor and two talks, continue with:

- [x]  Go to https://www.meetup.com/Ljubljana-Python-Group/, click on the upcoming meetup and post the following:

>Dear Python people of Ljubljana and beyond!
>
>We are glad to announce the speakers and sponsors for the upcoming Python meetup that will happen on [DAY] [DATE][HERE], at [TIME HERE] in [VENUE HERE]!
>
>Talks:
>
>[SPEAKER NAME AND TALK 1 TITLE HERE]
>
>[SPEAKER NAME AND TALK 2 TITLE HERE]
>
>After the talks you are welcome to stay around and participate in random discussions with fellow attendees.
> Free beer will be provided by [SPONSOR NAME HERE]
>
>More info and RSVP on [LINK TO MEETUP.COM EVENT HERE]
>
>See you there!

- [ ] Post announcement to https://www.facebook.com/groups/242976319229784/, https://www.facebook.com/groups/522926241218467/, https://www.facebook.com/groups/slotechstud/, https://www.facebook.com/groups/158003467603274/, https://www.facebook.com/groups/6884481293/, https://www.facebook.com/groups/353060628229741, https://www.facebook.com/groups/165720846803088.

- [ ]  Submit the event to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_event

- [ ] Tweet with @python_lj account:
Next #python #meetup in #ljubljana coming soon! [LINK TO MEETUP.COM EVENT HERE]

# Narrate the meetup

- [ ] Come to Računalniški muzej 20 minutes before the start of the meetup.

- [ ] Open up the Meetup.com event page on the projector so that new people know they are in the right place.

- [ ] Decide on a provisional date for next meetup.

- [ ] Ask each speaker for a sentence or two about who they are and what they do. Tell them you need this so you can introduce them.

- [ ]  Coordinate with speakers who will go first.

- [ ] If the sponsor is attending, ask them to prepare a 3 minute pitch about what they do and (potentially) who they are looking for.

- [ ]  The schedule is normally something along these lines. But feel free to improvise! (Obviously this is for non-virtual meetups, in case of a virtual one adapt accordingly)

      
     -  "Raise hand if you are new to this meetup".

     -  "Raise hand if you are new to Python".

     - Introduce the sponsor and give them 3 minutes for their pitch.

     - Cross out when you take a beer!

   
     - Introduce speaker 1.

     - Take a photo during talk 1.

     - Record number of attendees, number of RSVPs on meetup.com and weather to github issue for respective month (see     #25 for example).

     - Introduce speaker 2.

     - Take a photo during talk 2.

     - Thank speakers.

     - Open http://lmorillas.github.io/python_events, "raise hands who is going".
 
     - "We need talks: beginners welcome! web, mobile, desktop, embedded, big data, everything goes!"

     - "We need sponsors: give back to the community!"

     -  "Provisional date for next meetup, raise hands".

     - "Raise hands who is looking for work? Stand up who is hiring? Mingle!"

# Follow up

- [ ] Post photos to https://www.meetup.com/Ljubljana-Python-Group/

- [ ] Tweet best photo with @python_lj account, something like: 

> Good times yesterday at #ljubljana #python #meetup! <LINK TO MEETUP.COM EVENT HERE>

- [ ] Verify that the sponsor received invoice from Računalniški muzej.

**Comment by cmdctrlesc** [comment]
I can give a lightning talk, as promised, most likely on decorators in Python. But we are looking for full-length talks!  Additional lightning talks also welcome. 

Also, if you have information on whether having a live meetup is possible/a good idea at this time, feel free to comment.

**Comment by zupo** [comment]
Thanks for opening this! Can you also volunteer to narrate the meetup?

> Also, if you have information on whether having a live meetup is possible/a good idea at this time, feel free to comment.

Definitely not a good idea.

**Comment by kernc** [comment]
UL FRI hosted a few "picnic" meetups _outdoors_ beside its building where it was well ventilated, adequate in terms of distance keeping, and just plain awesome!

**Comment by cmdctrlesc** [comment]
@zupo I guess I can narrate, but I would ask you and/or @romunov to kind of watch over me and help me out if something goes wrong. 
@kernc this sounds really nice in theory, but it would probably be a pain to set up the projector and stuff...

**Comment by zupo** [comment]
Yeah, outdoors can work, but without talks I guess.

**Comment by romunov** [comment]
Not sure how complicated would it be to coordinate with Računalniški muzej to have a last minute schedule in case we feel confidant that the situation would be OK to meet in person. Right now I'm leaning more towards having this online for at least a little while.

**Comment by matejmeglic** [comment]
As speaking with Una ystrdy, I can have a talk about my Raspberry Pi Autonomous Timelapse Camera that I had been developing over the last couple of months.
Main topics:
- limitations of raspistill
- modifying first python script I found
- a "hackish" approach to code, getting to know PEP8 and 4 rewrites
- base camera functionalities
- product limitations
- further development (AWS, EternalCam)

**Comment by drorspei** [comment]
Yey fun!

How about Tuesday the 29th, at 7pm?

**Comment by stoteda** [comment]
Greetings, 

I recently moved to Ljubljana as managing director of a 5G mmWave company with a large R&D team in Ljubljana.  However, I have a strong interest in AI as well as 5G wireless.

For a short talk, I would like to discuss the development of chatbots with Python, and the importance of AI and chatbots in the future.  Over the next five years, 80% of communications will be done through automated means, robots if you will.  These robotic messengers will be in charge of facilitating business to consumer interaction, which will deliver a superior level of customer service.  

Using Python and Dialogflow frameworks, developers can build a cloud infrastructure for astoundingly intelligent chatbots. At the R42 Institute, a summer cohort of Fellows developed a chatbot for Covid communications, and this team can also be made available for discussion with the developers.

My interest also lies in getting a better understanding of the startup community in Ljubljana.  R42 has an investment arm that funds very early stage firms in AI, Communications and Biotech.

**Comment by drorspei** [comment]
Sounds great, the talk part and the robots communicating. 

So you can give the talk on the 29th? What title would you give it?

**Comment by matejmeglic** [comment]
Since this is a hobby-art project, here is a somewhat more visual draft presentation https://docs.google.com/presentation/d/14FUz_cFZTW0izWM1nycv-d-3myf_cw6tHen4O8BAduQ/edit?usp=sharing

I didn't want to put too much code in there as in that case, we would have a code review session.

**Comment by cmdctrlesc** [comment]
@matejmeglic looks awesome, looking forward!
