### ISSUE TITLE
🎄December 2020 meetup🎄

### ISSUE THREAD

**Issue by cmdctrlesc** [ljpy/meetups#48]
Attention, fellow Pythonistas! In this most festive of months, we are giving you the gift of another wonderful virtual meetup. Or better yet, you are giving the Python community the gift of your contribution! Comment your ideas for talks and dates bellow. 'Tis the season to get...Pythonic?

**Comment by jurecuhalev** [comment]
Some talks I could do:

- Utility first CSS (like Tailwind) - why is it useful and how it can help us prototype web sites faster
(probably best if it's a 'full' 20 min talk)
- gspread - https://gspread.readthedocs.io/en/latest/ - lightning talk about how library is nicer than manually parsing JSON

(pick one)

**Comment by kernc** [comment]
OT: 

> * Utility first CSS (like Tailwind)

Had to look this up.

![Screenshot_2020-11-11 Utility-First - Tailwind CSS](https://user-images.githubusercontent.com/684364/98866697-a39de000-246d-11eb-8f5c-c716d523a1c3.png)

And we've evolved full-circle back to styling in HTML. :+1: 

![Screenshot_2020-11-11 Utility-First - Tailwind CSS](https://user-images.githubusercontent.com/684364/98866791-c4663580-246d-11eb-8d2e-245ce7674194.png)

Perfect! :vomiting_face:

**Comment by zupo** [comment]
@kernc: It's super hard to find people willing to give a talk. Please be more respectful towards those that volunteer their free time to help others learn. You are very much welcome to submit a talk on how to do CSS in The Right Way™, and hopefully you convince some people to do it better.

**Comment by romunov** [comment]
Being HTML analphabet, I'd love to hear more about how to move fast and break things with inline CSS.

**Comment by samastur** [comment]
I'd prefer a talk on gspread, but either would be great.

**Comment by cmdctrlesc** [comment]
@zupo +1 
Also if this is such a controversial topic it seems to me that's all the more reason to give the talk and spark a (civilised and productive) discussion!

**Comment by cmdctrlesc** [comment]
The meeetup has been announced. All rejoice!

https://www.meetup.com/Ljubljana-Python-Group/events/274821208/
