### ISSUE TITLE
July 2017

### ISSUE THREAD

**Issue by zupo** [ljpy/meetups#5]
# Schedule the meetup

* [x] Talk with Marko from Poligon and choose a date/time when their venue is available. Standard time is Thursday at 7pm, but we don't mind some variation. Book it.
* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/ and use the `Schedule a new Meetup` link to schedule a new meetup.
    * [x] Enter `<Month> <Year>` as `What should we do?`
    * [x] Enter `More details:`. Template:
        ```
        Hi fellow Pythonistas!

        The next Python Meetup will take place on <DAY> <DATE HERE>, at <TIME HERE> in Poligon.

        Speakers: post a comment to https://github.com/ljpy/meetups/issues/1 or send an email to ljpy-organizers@googlegroups.com. First two people to do so get to share their ideas/tips/hacks/rants!

        Sponsors: post a comment to https://github.com/ljpy/meetups/issues/2 or send an email to ljpy-organizers@googlegroups.com. First one to do so gets to be the sponsor!


        See you soon!
        ```
    * [x] Select the booked date and time for the meetup.
    * [x] Select `Poligon` as location.
    * [x] When done click `Announce` so members of the user group are notified by email about the upcoming meetup.

# Announce the meetup

Wait a few days. If there are no sponsors and/or speakers that have stepped up, you will have to manually poke them to do so. Go through the list of potential [talks](https://github.com/ljpy/meetups/issues/1) and [sponsors](https://github.com/ljpy/meetups/issues/1). For speakers and sponsors, the rule is First-Come-First-Served: whoever comments on #1 or #2 first, gets to be the speaker/sponsor. Once you have a sponsor and two talks, continue with:

* [x] Go to https://www.meetup.com/Ljubljana-Python-Group/, click on the upcoming meetup and post the following:
    ```
    Dear Python people of Ljubljana and beyond!

    We are glad to announce the speakers and sponsors for the upcoming Python meetup that will happen on <DAY> <DATE HERE>, at <TIME HERE> in Poligon!

    Talks:
    
    <SPEAKER NAME AND TALK 1 TITLE HERE>

    <SPEAKER NAME AND TALK 2 TITLE HERE>

    After the talks you are welcome to stay around and participate in random discussions with fellow attendees. Free beer will be provided by <SPONSOR NAME HERE>!

    More info and RSVP on <LINK TO MEETUP.COM EVENT HERE>.


    See you there!
    ```
* [x] Post announcement to https://www.facebook.com/groups/242976319229784/, https://www.facebook.com/groups/522926241218467/, https://www.facebook.com/groups/slotechstud/, https://www.facebook.com/groups/158003467603274/, https://www.facebook.com/groups/6884481293/, https://www.facebook.com/groups/353060628229741, https://www.facebook.com/groups/165720846803088.
* [x] Submit the event to https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_event
* [x] Post a news item on slo-tech.com. (login, click `pošlji novico`)
* [x] Post an announcement to http://www.internetmojster.com/novice/.
* [x] Tweet with @python_lj account:
    ```
    Next #python #meetup in #ljubljana coming soon! <LINK TO MEETUP.COM EVENT HERE>
    ```

# Narrate the meetup

* [x] Come to Poligon 20 minutes before the start of the meetup.
* [x] Open up the Meetup.com event page on the projector so that new people know they are in the right place.
* [x] Decide on a provisional date for next meetup.
* [x] Ask each speaker for a sentence or two about who they are and what they do. Tell them you need this so you can introduce them.
* [x] Coordinate with speakers who will go first.
* [x] If the sponsor is attending, ask them to prepare a 3 minute pitch about what they do and (potentially) who they are looking for.
* [x] The schedule is normally something along these lines. Feel free to improvise:
  * [x] "Any international guests"? If yes, ask speakers to present in English if possible.
  * [x] "Please use #ljpy hashtag on social networks for shoutouts, comments, photos, etc.".
  * [x] "Raise hand if you are new to this meetup".
  * [x] "Raise hand if you are new to Python".
  * [x] Introduce the sponsor and give them 3 minutes for their pitch.
  * [x] Introduce speaker 1.
  * [x] Take a photo during talk 1.
  * [x] Introduce speaker 2.
  * [x] Take a photo during talk 2.
  * [x] Thank speakers.
  * [x] Open http://lmorillas.github.io/python_events, "raise hands who is going".
  * [x] "We need talks: beginners welcome! web, mobile, desktop, embedded, big data, everything goes!"
  * [x] "We need sponsors: give back to the community!"
  * [x] "Provisional date for next meetup, raise hands".
  * [x] "Raise hands who is looking for work? Stand up who is hiring? Mingle!"

# Follow up

* [x] Post photos to https://www.meetup.com/Ljubljana-Python-Group/
* [x] Tweet best photo with @python_lj account, something like:
    ```
    Good times yesterday at #ljubljana #python #meetup! <LINK TO MEETUP.COM EVENT HERE>
    ```
* [x] Verify that the sponsor received invoice from Poligon.

**Comment by zupo** [comment]
Provisional date is Thursday 20th July, right after EuroPython. Need to confirm with Poligon.

**Comment by zupo** [comment]
Date confirmed with Poligon.

**Comment by zupo** [comment]
Provisional sponsor is Bitstamp. Waiting for confirmation.

**Comment by zupo** [comment]
@lknix, @jmakov: can you help with finding the speakers for the next meetup? I'm totally tied up with personal things for the next week or so ...

**Comment by jmakov** [comment]
@zupo sure, I'll ask a couple of friends.

**Comment by zupo** [comment]
@lknix, @jmakov: Marko, who should have had his talk last month, stepped up again and will have it this time.

We need one more. And quick. The announcement should go out in a couple of days.

**Comment by jmakov** [comment]
@zupo I contacted @brodul and @plamut. Waiting for their answer...

**Comment by plamut** [comment]
I am out for July, sorry, as I would not be able to prepare a quality talk due to the attendance at EuroPython2017. But I am seriously contemplating giving a talk in late August.

**Comment by brodul** [comment]
I will have to excuse myself again. I am at EP2017 and will have to address some private stuff when I come back to Ljubljana.

**Comment by jmakov** [comment]
Contacted @Baveni, waiting for answer.

**Comment by jmakov** [comment]
@Baveni can't make it. I'll ping @meryuk and @avian2 otherwise if nobody steps up I can (again...) have a talk. @zupo I have a feeling you could also have interesting things to share. Care for a talk :)? Let me know who the other speaker is, it seems you're busy. If your busy and don't have time for organisational stuff I can fill in this week. Contact me if that's the case.

**Comment by zupo** [comment]
@jmakov:

1. I am still waiting for confirmation from Bitstamp that they can sponsor this meetup as well. Can you poke some people there? 
2. The other speaker is Marko Limbek, check your inbox.
3. Very busy indeed, 15-day old baby at home :). Would be great if you can take over this time. 
4. Sure, I'll prep a talk or three, as soon as things calm down a bit.

**Comment by jmakov** [comment]
@zupo:
1. Got the confirmation letter, tnx. Bitstamp has confirmed.
2. Great, tnx.
3. Np.
4. :+1: 

@avian2 stepped up and will be presenting "Merging structured data with jsonmerge". So it seems we have 2 presentations.

**Comment by zupo** [comment]
Great, please do the announcement! The instructions how are in the checklist above!


--
Excuse brevity, sent from a mobile device.

**Comment by zupo** [comment]
@jmakov: have a few free minutes now, will send out the announcement.

**Comment by zupo** [comment]
Ah I see you already made the post on Meetup. I'll do the FB posts now, then.

**Comment by jmakov** [comment]
@zupo tnx, I'm not in all groups yet. Also please tweet with @python_lj account. I don't have access. Also I can't click the check boxes :).

**Comment by zupo** [comment]
BTW, I didn't receive an email for your post on Meetup. Strange. Did you get it?

**Comment by jmakov** [comment]
Not yet. I didn't see any other option to post than to post a comment: https://www.meetup.com/Ljubljana-Python-Group/events/241019792/

**Comment by zupo** [comment]
Yep, this should be it.

**Comment by zupo** [comment]
Wait a few minutes I guess :)

**Comment by zupo** [comment]
Delivered now.
