### ISSUE TITLE
October 2021 virtual DragonPy meetup

### ISSUE THREAD

**Issue by romunov** [ljpy/meetups#51]
This is a placeholder for the October 2021 DragonPy meetup. For more information please see the [meetup.com page](https://www.meetup.com/Ljubljana-Python-Group/events/281056252).

To make things even more jam packed, we are looking for presenters who would be willing to give five minute lightning talks. Please contact us, preferably here.

**Comment by mlubej** [comment]
Hey!

I have two talks which overlap with Python:
- `graphviz` demo and examples
- `ffmpeg` demo and examples

In both cases I present the tool and then we learn about it through examples, ultimately showing how to do concrete stuff with python bindings for both.

The first one (`graphviz`) is shorter, cca. 10-15 min (double LT?), while the second one (`ffmpeg`) is a bit longer, perhaps good for a long talk (cca. 20 min).

I don't wish to trim them down to lightning talks, as the tools are huge and are already presented in a very slim fashion.

If there is a slot compatible for one or both of the talks, I'd like to give a presentation.

Cheers,
Matic

**Comment by HyoMiYing** [comment]
Hey!

I am interested for some time now, to give a lighting talk. Do I have to announce my theme in advance?

**Comment by cmdctrlesc** [comment]
@HyoMiYing yes, we need a title and a short description so we can add it to the [Meetup.com event](https://www.meetup.com/Ljubljana-Python-Group/events/281056252)

@mlubej awesome! Let's schedule this for the november meetup then, where you can have more time. You can drop me an email at alanxyz210@gmail.com for details.

**Comment by HyoMiYing** [comment]
@romunov 

I can give a lighting talk on one of these topics. It would be the best, if you could tell, which one sounds the most interesting, so I can adjust it to a 5 minute format (and also make a presentation).

1. Python kata, that took me 16 hours to finish (lahko se sprav v 5 minuten format, ker je algoritmični problem precej preprost, le razumevanje problema mi je vzelo ogromno časa, ter optimizacija. Pomoje bi bilo to zanimivo za poslušat/gledat, ker ponavadi ljudje na meetupih govorijo le o paketih, in kako/kdaj/kaj uporabit. Če bi nekdo drug naredil 5-minuten sprehod skozi nek problem, bi ga jaz z veseljem poslušal =) )
2. How design for my client changed from first demands, to final negotiation (to ni Python, ampak je povezan, saj je Python v veliko backend strani, in poznam nekaj ljudi iz meetupov, ki so primarno web-developerji. To bi bil precej sproščen in mentalno ne-zahteven govor. Predstavil bi klientove želje na začetku, in s čim je bil zadovoljen na koncu, ter vmesni proces (delal sem z dvema dezajnerjoma, oba sem plačal, in je zanimivo, kako se je dezajn vmes spreminjal - to je talk, ki bi ga še najlažje izvedel, in bi ga še najraje predstavil... Vendar mi prosim sporočite, če je tema dovolj primerna... (glede na to, da je to le 5 minutni talk, bi pomoje to lahko naredil, saj bi bilo za vse zanimivo )) P.S.: Klient mi je dovolil, da uporabim dezajn za predstavitvene namene
3. Predstavitev mojega načina uporabe Funkcionalnih testov, česar se m se naučil v knjigi 'Test Driven Development in Python'  (imel bi live code demo) projekta, ki sem ga [že naredil v preteklosti](https://rok-klancar.com/project_sticker)

**Comment by HyoMiYing** [comment]
@cmdctrlesc @romunov 

Hello!
Please, I need an answer to my talk proposal ☝️☝️☝️
I cannot just prepare all 3 talks for this event and then let the audience choose then and there - especially if i'll be doing live code demonstration. You know how that is 😂😂😂

**Comment by zupo** [comment]
I'd like to hear all three, really. So just choose one, and then let's do others next time.

**Comment by HyoMiYing** [comment]
@zupo Okay, thank you, your compliment is music to my ears 😁

I will choose one myself. And I hope it won't be problem that I will attend the meetup from ~20:30h onward, since I work untill ~20h on wednesday. The lighting talks are still at the end of the meetup, right?

**Comment by romunov** [comment]
@HyoMiYing sorry for the radio silence, but this weekend was lights out weekend.
As @zupo said, let's hear all of them. My vote is to have (2) next.

**Comment by cmdctrlesc** [comment]
@HyoMiYing do you have the description/title for wednesday's talk?  Then for the next one (november) we can talk at the meetup, pick suitable dates etc. We're very happy you have so many cool ideas!

**Comment by HyoMiYing** [comment]
@cmdctrlesc 

Title: A Python excercise worth considering

Description: Rok takes 5 minutes to present to you a very interesting Python coding exercise, and also invites you to do it better than he did =)

See you in the evening =)
